spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: dips-auth
        uri: lb://dips-auth
        predicates:
        - Path=/auth/**
        filters:
          # 验证码处理
        - ImageCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
      #UPMS 模块
      - id: dips-upms
        uri: lb://dips-upms
        predicates:
        - Path=/admin/**
        filters:
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
         # 降级配置
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'
      #标签模块
      - id: dips-tms
        uri: lb://dips-tms
        predicates:
        - Path=/tms/**
        filters:
          # 限流配置
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@remoteAddrKeyResolver}'
            redis-rate-limiter.replenishRate: 10
            redis-rate-limiter.burstCapacity: 20
      # 代码生成模块
      - id: dips-codegen
        uri: lb://dips-codegen
        predicates:
        - Path=/gen/**
      - id: gds-cleaning
        uri: lb://gds-cleaning
        predicates:
        - Path=/dataclean/**
      - id: gds-preprocessing
        uri: lb://gds-preprocessing
        predicates:
        - Path=/preprocessing/**
security:
  encode:
    # 前端密码密钥，必须16位
    key: 'dipscloudisbest1'
# 不校验验证码终端
ignore:
  clients:
    test
