# spring security 配置
security:
  oauth2:
    client:
      client-id: dips
      client-secret: dips
      scope: server
debug: false
logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      cloud:
        gds:
          gms: DEBUG

# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Gov20130528
    #数据库
    url: jdbc:mysql://118.31.60.34:3306/dips_cloud_gov?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

# swagger相关配置,覆盖全局配置
swagger:
  authorization:
    authorization-scope-list:
    -   scope: 'server'
        description: 'server all'
    -   scope: 'read'
        description: 'read all'
    -   scope: 'write'
        description: 'access all'
